### ISSUE TITLE
🐛 [BUG]: Missing "./server.js" export in "react-dom" package

### ISSUE THREAD

**Issue by binary64** [nxtensions/nxtensions#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What package does the issue affects?

@nxtensions/astro

### Describe the bug

`pnpm nx run astro-docs:dev` launched the server:

```
> nx run astro-docs:dev

02:43 [astro] Server started                               253ms
02:43 [astro] Local: http://::1:3000/
02:44:12 [vite] Error when evaluating SSR module @astrojs/renderer-react/server.js:
Error: Missing "./server.js" export in "react-dom" package
    at bail (C:\Users\User\nx-demo\node_modules\.pnpm\vite@2.9.12_less@3.12.2+stylus@0.55.0\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:38572:8)
    at resolve (C:\Users\User\nx-demo\node_modules\.pnpm\vite@2.9.12_less@3.12.2+stylus@0.55.0\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:38649:10)
    at resolveExports (C:\Users\User\nx-demo\node_modules\.pnpm\vite@2.9.12_less@3.12.2+stylus@0.55.0\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:40957:12)  
    at resolveDeepImport (C:\Users\User\nx-demo\node_modules\.pnpm\vite@2.9.12_less@3.12.2+stylus@0.55.0\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:40975:31)
    at tryNodeResolve (C:\Users\User\nx-demo\node_modules\.pnpm\vite@2.9.12_less@3.12.2+stylus@0.55.0\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:40756:20)  
    at viteResolve (C:\Users\User\nx-demo\node_modules\.pnpm\vite@2.9.12_less@3.12.2+stylus@0.55.0\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:50308:26)     
    at nodeImport (C:\Users\User\nx-demo\node_modules\.pnpm\vite@2.9.12_less@3.12.2+stylus@0.55.0\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:50345:15)      
    at ssrImport (C:\Users\User\nx-demo\node_modules\.pnpm\vite@2.9.12_less@3.12.2+stylus@0.55.0\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:50241:20)       
    at eval (@astrojs/renderer-react/server.js:5:37)
    at async instantiateModule (C:\Users\User\nx-demo\node_modules\.pnpm\vite@2.9.12_less@3.12.2+stylus@0.55.0\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:50286:9)
02:44 [astro] 500 /
```

### Expected behavior

Launch but without the crash

### Steps to reproduce

```bash
cd ~ && npm i -g pnpm create-nx-workspace && \
rm -rf ~/nx-demo && \
cd ~/ && \
npx create-nx-workspace nx-demo --packageManager=pnpm --style=less --nx-cloud=false --interactive=false --preset=empty --linter=eslint && \
cd nx-demo && \
pnpm add -D @nxtensions/astro @astrojs/renderer-svelte @astrojs/renderer-vue @astrojs/renderer-react @astrojs/renderer-preact preact-render-to-string && \
pnpm nx generate @nxtensions/astro:app astro-docs && \
pnpm nx run astro-docs:dev
```

### Environment

Node : 17.9.0
   OS   : win32 x64
   pnpm : 7.2.1

   nx : 14.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.2.4
   @nrwl/detox : 14.2.4
   @nrwl/devkit : 14.2.4
   @nrwl/eslint-plugin-nx : 14.2.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.4
   @nrwl/js : 14.2.4
   @nrwl/linter : 14.2.4
   @nrwl/nest : 14.2.4
   @nrwl/next : 14.2.4
   @nrwl/node : 14.2.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.2.4
   @nrwl/react-native : 14.2.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.4
   @nrwl/web : 14.2.4
   @nrwl/workspace : 14.2.4
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @nx-plus/docusaurus: 14.0.0
         @nxtensions/astro: 2.2.0

**Comment by leosvelperez** [comment]
This should have been solved in the latest version of the plugin.

I'm gonna close this but feel free to reopen it or leave a comment if you still have issues with this.
