### ISSUE TITLE
🐛 [BUG]: Application Generator Is Failing on setupE2E

### ISSUE THREAD

**Issue by techguysimon** [nxtensions/nxtensions#557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What package does the issue affects?

@nxtensions/astro

### Describe the bug

I get the error below when attempting to generate an application in a fresh repo

```

>  NX  Generating @nxtensions/astro:application

✔ What frameworks and/or addons would you like to enable? · No items were selected
In Nx 19, generating projects will no longer derive the name and root.
Please provide the exact project name and root in the future.
Example: nx g @nx/cypress:cypress-project idrivesocal-idrivesocal-e2e --directory apps/idrivesocal/idrivesocal-e2e

 >  NX   Cannot find configuration for 'apps-idrivesocal-idrivesocal-e2e'


Error: Cannot find configuration for 'apps-idrivesocal-idrivesocal-e2e'
    at readProjectConfiguration (/Users/simon/code/personal/bluebeast-clients/tom-smith-monorepo/tomsmith/node_modules/nx/src/generators/utils/project-configuration.js:99:15)
    at setupE2ETests (/Users/simon/code/personal/bluebeast-clients/tom-smith-monorepo/tomsmith/node_modules/@nxtensions/astro/src/generators/application/utilities/setup-e2e-tests.js:24:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async applicationGenerator (/Users/simon/code/personal/bluebeast-clients/tom-smith-monorepo/tomsmith/node_modules/@nxtensions/astro/src/generators/application/generator.js:25:21)
    at async /Users/simon/code/personal/bluebeast-clients/tom-smith-monorepo/tomsmith/node_modules/nx/src/command-line/generate/generate.js:241:26
    at async handleErrors (/Users/simon/code/personal/bluebeast-clients/tom-smith-monorepo/tomsmith/node_modules/nx/src/utils/params.js:9:16)
    at async Object.handler (/Users/simon/code/personal/bluebeast-clients/tom-smith-monorepo/tomsmith/node_modules/nx/src/command-line/generate/command-object.js:13:22)
```

I had to comment edit the generator file to skip the e2e setup in order move forward for now

### Expected behavior

The application and e2e test should be generated.

### Steps to reproduce

```
"devDependencies": {
    "@nx/cypress": "18.0.4",
    "@nx/js": "18.0.4",
    "@nx/node": "^18.0.4",
    "@nxtensions/astro": "^18.0.0",
    "@swc-node/register": "~1.8.0",
    "@swc/core": "~1.3.85",
    "@swc/helpers": "~0.5.2",
    "astro": "^4.3.5",
    "cypress": "^13.0.0",
    "nx": "18.0.4",
    "prettier": "^2.6.2",
    "typescript": "~5.3.2"
  },
  ```
  `nx generate @nxtensions/astro:app --name=myapp --directory="apps/myapp" --dryRun --verbose`

### Environment

```

 >  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : darwin-arm64
   npm    : 10.1.0

   nx (global)    : 18.0.4
   nx             : 18.0.4
   @nx/js         : 18.0.4
   @nx/jest       : 18.0.4
   @nx/linter     : 18.0.4
   @nx/eslint     : 18.0.4
   @nx/workspace  : 18.0.4
   @nx/cypress    : 18.0.4
   @nx/devkit     : 18.0.4
   @nx/node       : 18.0.4
   @nrwl/tao      : 18.0.4
   typescript     : 5.3.3
   ---------------------------------------
   Community plugins:
   @nxtensions/astro : 18.0.0

```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I'll fix this over the weekend. In the meantime, you can also run `nx generate @nxtensions/astro:app --name=myapp --directory="apps/myapp" --no-add-cypress-tests` or `nx generate @nxtensions/astro:app --name=myapp --directory="apps/myapp" --add-cypress-tests=false` to disable generating the e2e setup. There's no need to edit the generator file.

**Comment by techguysimon** [comment]
Thanks. I couldn't figure out the cli property needed to do that.
