### ISSUE TITLE
🐛 [BUG]: Astro plugin fails with Nx 19.1.2

### ISSUE THREAD

**Issue by cgranados16** [nxtensions/nxtensions#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What package does the issue affects?

@nxtensions/astro

### Describe the bug

Enabling this plugin with Nx 19.1.2 causes Nx to fail. This breaks Nx completely and every command returns a `Failed to process project graph.` error. This affects versions 19.1.2 up to latest(19.2.0).

Opening the Nx Graph in VS Code shows:
```
 The "@nxtensions/astro" plugin threw an error while creating dependencies:
    TypeError: targetProjectLocator.findProjectWithImport is not a function
      at .../node_modules/@nxtensions/astro/src/project-graph/create-dependencies.js:55:55
      at TypeScriptImportLocator.fromNode (.../node_modules/nx/src/plugins/js/project-graph/build-dependencies/typescript-import-locator.js:41:17)
      at .../node_modules/nx/src/plugins/js/project-graph/build-dependencies/typescript-import-locator.js:80:53
      at visitNodes (.../node_modules/typescript/lib/typescript.js:28321:24)
      at forEachChildInSourceFile (.../node_modules/typescript/lib/typescript.js:28964:18)
      at Object.forEachChild (.../node_modules/typescript/lib/typescript.js:28406:37)
      at TypeScriptImportLocator.fromNode (.../node_modules/nx/src/plugins/js/project-graph/build-dependencies/typescript-import-locator.js:80:18)
      at collectDependencies (.../node_modules/@nxtensions/astro/src/project-graph/create-dependencies.js:52:23)
      at collectDependencies (.../node_modules/@nxtensions/astro/src/project-graph/create-dependencies.js:71:15)
      at Object.createDependencies (.../node_modules/@nxtensions/astro/src/project-graph/create-dependencies.js:30:19)
```

Removing the plugin from the plugins option in the `nx.json` file fix it.
```json
"plugins": [
    "@nxtensions/astro",
]
```

### Expected behavior

Nx should be able to build the Astro project 

### Steps to reproduce

1. Create a new Nx workspace using the `@nxtensions/astro` plugin
```
npx create-nx-workspace@latest --preset=@nxtensions/astro
```

### Environment

``` 
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
```

Running
```zsh
> nx --version
```
returns
```
Nx Version:
- Local: v19.1.2
- Global: v19.2.0
```

**Comment by andersonba** [comment]
`findProjectWithImport` was renamed to `findProjectFromImport` in https://github.com/nrwl/nx/pull/23307/files#diff-6120d1e1d8228cc6caee07dae7c2c4fa47b74095d60f51797cc2c5b47dc6f1a9R76 😮‍💨

**Comment by dmastag** [comment]
Would it be possible to Review #646 so this one can be closed ?
